use serde::Serialize;
use url::form_urlencoded;

use crate::torrent::Torrent;

#[derive(Debug, Serialize)]
pub struct TrackerRequest {
    /// Urlencoded 20-byte SHA1 hash of the value of the info key from the Metainfo file.
    /// Note that the value will be a bencoded dictionary, given the definition of the info key above.
    #[serde(rename = "info_hash")]
    info_hash_encoded: String,

    /// Urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup.
    /// This is allowed to be any value, and may be binary data. There are currently no guidelines for generating this peer ID.
    /// However, one may rightly presume that it must at least be unique for your local machine, thus should probably incorporate things like process ID and perhaps a timestamp recorded at startup.
    #[serde(rename = "peer_id")]
    peer_id_encoded: String,

    /// The port number that the client is listening on. Ports reserved for BitTorrent are typically 6881-6889.
    /// Clients may choose to give up if it cannot establish a port within this range.
    port: u16,

    /// The total amount uploaded (since the client sent the 'started' event to the tracker) in base ten ASCII.
    /// While not explicitly stated in the official specification,
    /// the concensus is that this should be the total number of bytes uploaded.
    uploaded: u64,

    /// The total amount downloaded (since the client sent the 'started' event to the tracker) in base ten ASCII.
    /// While not explicitly stated in the official specification,
    /// the consensus is that this should be the total number of bytes downloaded.
    downloaded: u64,

    /// The number of bytes this client still has to download in base ten ASCII.
    /// Clarification: The number of bytes needed to download to be 100% complete and get all the included files in the torrent.
    left: u64,

    /// Setting this to 1 indicates that the client accepts a compact response.
    ///
    /// The peers list is replaced by a peers string with 6 bytes per peer.
    /// The first four bytes are the host (in network byte order), the last two bytes are the port (again in network byte order).
    /// It should be noted that some trackers only support compact responses (for saving bandwidth) and either refuse requests without "compact=1" or simply send a compact response unless the request contains "compact=0" (in which case they will refuse the request.)
    compact: u8,

    /// If specified, must be one of started, completed, stopped, (or empty which is the same as not being specified).
    /// If not specified, then this request is one performed at regular intervals.
    #[serde(skip_serializing_if = "Option::is_none")]
    event: Option<Event>,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]
enum Event {
    Started,
    Stopped,
    Completed,
}

// my Skill issue: learn to use the fully serde way of serializing
impl Serialize for Event {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Event::Started => serializer.serialize_str("started"),
            Event::Stopped => serializer.serialize_str("stopped"),
            Event::Completed => serializer.serialize_str("completed"),
        }
    }
}

impl std::fmt::Display for Event {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Event::Started => write!(f, "started"),
            Event::Stopped => write!(f, "stopped"),
            Event::Completed => write!(f, "completed"),
        }
    }
}

impl TrackerRequest {
    pub fn new(torrent: &Torrent, info_hash: &[u8; 20], peer_id: &str, port: u16) -> Self {
        // handle single-file vs multi-file
        let left = if let Some(l) = torrent.info.length {
            l
        } else if let Some(files) = &torrent.info.files {
            files.iter().map(|file| file.length).sum()
        } else {
            // invalid torrent(or maybe empty?)
            0
        };

        let info_hash_encoded: String = form_urlencoded::byte_serialize(info_hash).collect();
        let peer_id_encoded: String = form_urlencoded::byte_serialize(peer_id.as_bytes()).collect();

        Self {
            info_hash_encoded,
            peer_id_encoded,
            port,
            uploaded: 0,
            downloaded: 0,
            left,
            compact: 1,
            event: Some(Event::Started),
        }
    }

    pub fn as_query_string(&self) -> String {
        let mut url = format!(
            "info_hash={}&peer_id={}&port={}&uploaded={}&downloaded={}&left={}&compact={}",
            self.info_hash_encoded,
            self.peer_id_encoded,
            self.port,
            self.uploaded,
            self.downloaded,
            self.left,
            self.compact,
        );

        if let Some(event) = &self.event {
            url.push_str(&format!("&event={}", event));
        }

        url
    }
}
